# Use the official OpenJDK 8 image as a base image
FROM openjdk:8-jdk-alpine

# install maven
RUN apk add --no-cache maven

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Build the application
RUN mvn clean package

# Expose port 8081
EXPOSE 8081

# Define the entry point for the application
ENTRYPOINT ["java", "-jar", "target/payment-validation-service.jar"]