# MySQL DB for Payments

# Use the official MySQL image as the base image
FROM mysql:latest

# Set the root user and password
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Copy the SQL scripts into the container
COPY paymentsdb.sql /docker-entrypoint-initdb.d/
COPY trustlydb.sql /docker-entrypoint-initdb.d/
COPY validationsdb.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306

# Command to run when the container starts
CMD ["mysqld"]
